config/routes.rb
Skillz::Application.routes.draw do

  root :to => "Users#index"

  get '/offers/new', controller: 'offers', action: 'new', as: 'new_offer'
  post '/offers', controller: 'offers', action: 'create'

  get '/offers', controller: 'offers', action: 'index', as: 'offers'
  get '/offers/:id', controller: 'offers', action: 'show', as: 'offer'

  get '/offers/:id/edit', controller: 'offers', action: 'edit', as: 'edit_offer'
  put '/offers/:id', controller: 'offers', action: 'update'
  post '/offers/:id/accept', controller: 'offers', action: 'accept', as: 'accept_offer'

  delete '/offers/:id', controller: 'offers', action: 'destroy'

  get '/skills/new', controller: 'skills', action: 'new', as: 'new_skill'
  post '/skills', controller: 'skills', action: 'create'

  get '/skills', controller: 'skills', action: 'index', as: 'skills'
  get '/skills/:id', controller: 'skills', action: 'show', as: 'skill'

  get '/skills/:id/edit', controller: 'skills', action: 'edit', as: 'edit_skill'
  put '/skills/:id', controller: 'skills', action: 'update'

  delete '/skills/:id', controller: 'skills', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :skill
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :skills
  has_many :offers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def index
    @offers = Offer.all
  end

  def show
    @offer = Offer.find_by_id(params[:id])
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new
    @offer.user_id = params[:user_id]
    @offer.skill_id = params[:skill_id]
    @offer.other_user_id = params[:other_user_id]
    @offer.other_skill_id = params[:other_skill_id]

    if @offer.save
            redirect_to offers_url
          else
      render 'new'
    end
  end

  def edit
    @offer = Offer.find_by_id(params[:id])
  end

  def update
    @offer = Offer.find_by_id(params[:id])
    @offer.user_id = params[:user_id]
    @offer.skill_id = params[:skill_id]
    @offer.other_user_id = params[:other_user_id]
    @offer.other_skill_id = params[:other_skill_id]

    if @offer.save
            redirect_to offers_url
          else
      render 'edit'
    end
  end

  def destroy
    @offer = Offer.find_by_id(params[:id])
    @offer.destroy
        redirect_to offers_url
      end

  def accept
    o = Offer.find_by_id(params[:offer_id])
    o.accepted= true
    o.save

    redirect_to user_path(params[:user_id])
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find_by_id(params[:id])
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new
    @skill.task = params[:task]
    @skill.user_id = params[:user_id]
    
    if @skill.save
            redirect_to skills_url
          else
      render 'new'
    end
  end

  def edit
    @skill = Skill.find_by_id(params[:id])
  end

  def update
    @skill = Skill.find_by_id(params[:id])
    @skill.task = params[:task]
    @skill.user_id = params[:user_id]
    
    if @skill.save
            redirect_to skills_url
          else
      render 'edit'
    end
  end

  def destroy
    @skill = Skill.find_by_id(params[:id])
    @skill.destroy
        redirect_to skills_url
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.username = params[:username]
    @user.email = params[:email]
    @user.bio = params[:bio]
    
    if @user.save
            redirect_to users_url
          else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.username = params[:username]
    @user.email = params[:email]
    @user.bio = params[:bio]
    
    if @user.save
            redirect_to users_url
          else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
        redirect_to users_url
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Skillz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/">Skillz</a>
        <div class="nav-collapse">
          <ul class="nav">

            <li><%= link_to "Home", "/" %></li>
            <li><%= link_to "Users", "/users" %></li>
            <li><%= link_to "Skills", "/skills" %></li>
            <li><%= link_to "Offers", "/offers" %></li>
            <li><a href="#about">About</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
    <% end %>

    <%= yield %>

    <hr>

    <footer>
      <p>&copy; Company 2012</p>
    </footer>

  </div>

</body>
</html>

app/views/offers/edit.html.erb
<h1>Editing Offer #<%= @offer.id %></h1>


<%= form_tag(offer_url(@offer), method: 'put') do %>

  <div>
    <%= label_tag :user_id %><br />
    <%= number_field_tag :user_id, @offer.user_id %>
  </div>

  <div>
    <%= label_tag :skill_id %><br />
    <%= number_field_tag :skill_id, @offer.skill_id %>
  </div>

  <div>
    <%= label_tag :other_user_id %><br />
    <%= number_field_tag :other_user_id, @offer.other_user_id %>
  </div>

  <div>
    <%= label_tag :other_skill_id %><br />
    <%= number_field_tag :other_skill_id, @offer.other_skill_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Offer" %>
  </div>

<% end %>

app/views/offers/index.html.erb
<h1>Offers</h1>

<p><%= link_to 'Add a New Offer', new_offer_url %></p>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Skill</th>
      <th>Other user</th>
      <th>Other skill</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @offers.each do |offer| %>
    <tr>
      <td><%= offer.user.username %></td>
      <td><%= offer.skill.task %></td>
      <td><%= offer.user.username %></td>
      <td><%= offer.skill.task %></td>

      <td><%= link_to 'Show', offer_url(offer) %></td>
      <td><%= link_to 'Edit', edit_offer_url(offer) %></td>
      <td><%= link_to 'Destroy', offer_url(offer), method: 'delete', data: { confirm: "Do you really want to delete this offer?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/offers/new.html.erb
<h1>New Offer</h1>


<%= form_tag(offers_url, method: 'post') do %>


  <div>
    <%= label_tag :user_id %><br />
    <%= select_tag :user_id, options_from_collection_for_select(User.all, "id", "username") %>
  </div>

    <div>
    <%= label_tag :skill_id %><br />
    <%= select_tag :skill_id, options_from_collection_for_select(Skill.all, "id", "task") %>

  </div>

    <div>
    <%= label_tag :other_user_id %><br />
    <%= select_tag :other_user_id, options_from_collection_for_select(User.all, "id", "username") %>
  </div>

    <div>
    <%= label_tag :other_skill_id %><br />
    <%= select_tag :other_skill_id, options_from_collection_for_select(Skill.all, "id", "task") %>
  </div>


  <div>
    <%= submit_tag "Create Offer" %>
  </div>
<% end %>

app/views/offers/show.html.erb
<h1>Offer #<%= @offer.id %></h1>

<p>
  <b>User:</b>
  <%= @offer.user_id %>
</p>

<p>
  <b>Skill:</b>
  <%= @offer.skill_id %>
</p>

<p>
  <b>Other user:</b>
  <%= @offer.other_user_id %>
</p>

<p>
  <b>Other skill:</b>
  <%= @offer.other_skill_id %>
</p>

app/views/skills/edit.html.erb
<h1>Editing Skill #<%= @skill.id %></h1>


<%= form_tag(skill_url(@skill), method: 'put') do %>

  <div>
    <%= label_tag :task %><br />
    <%= text_area_tag :task, @skill.task %>
  </div>

  <div>
    <%= label_tag :user_id %><br />
    <%= text_field_tag :user_id, @skill.user_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Skill" %>
  </div>

<% end %>

app/views/skills/index.html.erb
<h1>Skills</h1>

<p><%= link_to 'Add a New Skill', new_skill_url %></p>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @skills.each do |skill| %>
    <tr>
      <td><%= skill.task %></td>
      <td><%= skill.user.username %></td>

      <td><%= link_to 'Show', skill_url(skill) %></td>
      <td><%= link_to 'Edit', edit_skill_url(skill) %></td>
      <td><%= link_to 'Destroy', skill_url(skill), method: 'delete', data: { confirm: "Do you really want to delete this skill?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/skills/new.html.erb
<h1>New Skill</h1>


<%= form_tag(skills_url, method: 'post') do %>


  <div>
    <%= label_tag :task %><br />
    <%= text_area_tag :task %>
  </div>

    <div>
    <%= label_tag :user_id %><br />
      <%= select_tag :user_id, options_from_collection_for_select(User.all, :id, :username) %>
  </div>


  <div>
    <%= submit_tag "Create Skill" %>
  </div>
<% end %>

app/views/skills/show.html.erb
<h1>Skill #<%= @skill.id %></h1>

<p>
  <b>Task:</b>
  <%= @skill.task %>
</p>

<p>
  <b>User:</b>
  <%= @skill.user %>

</p>

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :username %><br />
    <%= text_field_tag :username, @user.username %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

  <div>
    <%= label_tag :bio %><br />
    <%= text_area_tag :bio, @user.bio %>
  </div>

  
  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Bio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.bio %></td>
  
      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :username %><br />
    <%= text_field_tag :username %>
  </div>

    <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

    <div>
    <%= label_tag :bio %><br />
    <%= text_area_tag :bio %>
  </div>

  
  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User: #<%= @user.id %></h1>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Bio:</b>
  <%= @user.bio %>
</p>

<p>
  <b>Skills:</b>
  <% @user.skills.each do |s| %>
  <%= s.task %><br>
  <% end %>
</p>
<p>
  <b>Offers:</b><br/>
  <% @user.offers.each do |o| %>
    <%= User.find_by_id(o.other_user_id).username %> is offering to <%= Skill.find_by_id(o.other_skill_id).task %> in exchange for <%= Skill.find_by_id(o.skill_id).task %>

     <%= form_tag accept_offer_path do %>
        <%= hidden_field_tag :offer_id, o.id %>
        <%= hidden_field_tag :user_id, @user.id %>
        <%= submit_tag 'Accept' %>
      <% end %>
      <% if o.accepted == true %><p>The offer has been accepted!</p><% end %>
  <% end %>


</p>